-- MySQL Script generated by MySQL Workbench
-- Mon 26 Dec 2016 15:05:30 NZDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema madeIn
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `madeIn`.`manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`manufacturer` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`manufacturer` (
  `manuid` INT NOT NULL AUTO_INCREMENT,
  `manufacturername` TEXT NULL,
  `idcountryman` INT NOT NULL,
  PRIMARY KEY (`manuid`),
  CONSTRAINT `fk_address_countries3`
    FOREIGN KEY (`idcountryman`)
    REFERENCES `madeIn`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  
ENGINE = InnoDB;

CREATE INDEX `fk_address_countries3_idx` ON `madeIn`.`manufacturer` (`idcountryman` ASC);
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE UNIQUE INDEX `idmanufacturer_UNIQUE` ON `madeIn`.`manufacturer` (`manuid` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`products` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productname` TEXT NULL,
  `barcode` VARCHAR(40),
  `idmanufacturer` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_manufacturer1`
    FOREIGN KEY (`idmanufacturer`)
    REFERENCES `madeIn`.`manufacturer` (`manuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `madeIn`.`products` (`id` ASC);

CREATE INDEX `fk_products_manufacturer1_idx` ON `madeIn`.`products` (`idmanufacturer` ASC);

-- -----------------------------------------------------
-- Table `madeIn`.`city`
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `madeIn`.`factory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`factory` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`factory` (
  `factoryid` INT NOT NULL AUTO_INCREMENT,
  `factoryname` TEXT NULL,
  PRIMARY KEY (`factoryid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idfactory_UNIQUE` ON `madeIn`.`factory` (`factoryid` ASC);



-- -----------------------------------------------------
-- Table `madeIn`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`address` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL,
  `city` INT NOT NULL,
  `state` INT NOT NULL,
  `country` INT NOT NULL,
  `zip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city`)
    REFERENCES `madeIn`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_countries1`
    FOREIGN KEY (`country`)
    REFERENCES `madeIn`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_state1`
    FOREIGN KEY (`state`)
    REFERENCES `madeIn`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_address_city1_idx` ON `madeIn`.`address` (`city` ASC);

CREATE INDEX `fk_address_countries1_idx` ON `madeIn`.`address` (`country` ASC);

CREATE INDEX `fk_address_state1_idx` ON `madeIn`.`address` (`state` ASC);

CREATE UNIQUE INDEX `idusers_UNIQUE` ON `madeIn`.`address` (`id` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`manufacturer_factory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`manufacturer_factory` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`manufacturer_factory` (
  `idmanufacturer` INT NULL,
  `idfactory` INT NULL,
  CONSTRAINT `fk_manufacturer_factory_manufacturer1`
    FOREIGN KEY (`idmanufacturer`)
    REFERENCES `madeIn`.`manufacturer` (`manuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manufacturer_factory_factory1`
    FOREIGN KEY (`idfactory`)
    REFERENCES `madeIn`.`factory` (`factoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_manufacturer_factory_manufacturer1_idx` ON `madeIn`.`manufacturer_factory` (`idmanufacturer` ASC);

CREATE INDEX `fk_manufacturer_factory_factory1_idx` ON `madeIn`.`manufacturer_factory` (`idfactory` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`factory_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`factory_address` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`factory_address` (
  `idfactory` INT NOT NULL,
  `idaddress` INT NOT NULL,
  CONSTRAINT `fk_factory_address_factory1`
    FOREIGN KEY (`idfactory`)
    REFERENCES `madeIn`.`factory` (`factoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factory_address_address1`
    FOREIGN KEY (`idaddress`)
    REFERENCES `madeIn`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_factory_address_factory1_idx` ON `madeIn`.`factory_address` (`idfactory` ASC);

CREATE INDEX `fk_factory_address_address1_idx` ON `madeIn`.`factory_address` (`idaddress` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`users` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`users` (
  `usersname` VARCHAR(16) NULL,
  `email` VARCHAR(255) NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `usersid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usersid`));

CREATE UNIQUE INDEX `idusers_UNIQUE` ON `madeIn`.`users` (`usersid` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`contribution_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`contribution_type` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`contribution_type` (
  `idcontribution` INT NOT NULL AUTO_INCREMENT,
  `contriname` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontribution`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madeIn`.`product_contributor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`product_contributor` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`product_contributor` (
  `idproducts` INT NULL,
  `idusers` VARCHAR(255) NOT NULL,
  `contribution_type` INT NULL,
  CONSTRAINT `fk_product_contributor_users1`
    FOREIGN KEY (`idusers`)
    REFERENCES `madeIn`.`users` (`usersid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_contributor_products1`
    FOREIGN KEY (`idproducts`)
    REFERENCES `madeIn`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_contributor_contribution_type1`
    FOREIGN KEY (`contribution_type`)
    REFERENCES `madeIn`.`contribution_type` (`idcontribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_contributor_users1_idx` ON `madeIn`.`product_contributor` (`idusers` ASC);

CREATE INDEX `fk_product_contributor_products1_idx` ON `madeIn`.`product_contributor` (`idproducts` ASC);

CREATE INDEX `fk_product_contributor_contribution_type1_idx` ON `madeIn`.`product_contributor` (`contribution_type` ASC);

-- -----------------------------------------------------
-- Table `madeIn`.`categories`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `madeIn`.`categories`;

CREATE TABLE IF NOT EXISTS `madeIn`.`categories` (
    `idcat` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(60),
    PRIMARY KEY (`idcat`));

CREATE UNIQUE INDEX `idcategories_UNIQUE` ON `madeIn`.`categories` (`idcat` ASC);

-- -----------------------------------------------------
-- table product_category
-- -----------------------------------------------------

DROP TABLE IF EXISTS `madeIn`.`product_category`;

CREATE TABLE IF NOT EXISTS `madeIn`.`product_category` (
    `idcategory` INT NOT NULL,
    `idproductcat` INT NOT NULL,
    CONSTRAINT `fk_product_category_idproductcat1`
        FOREIGN KEY (`idproductcat`)
        REFERENCES `madeIn`.`products` (`id`),
    CONSTRAINT `fk_product_category_idcategory1`
        FOREIGN KEY (`idcategory`)
        REFERENCES `madeIn`.`categories` (`idcat`)
);

-- -----------------------------------------------------
-- Table product_factory
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`product_factory`;

CREATE TABLE IF NOT EXISTS `madeIn`.`product_factory` (
    `idproduct` INT NOT NULL,
    `idfactory` INT NOT NULL,
    CONSTRAINT `fk_product_factory_idproduct1`
        FOREIGN KEY (`idproduct`)
        REFERENCES `madeIn`.`products` (`id`),
    CONSTRAINT `fk_product_factory_idfactory1`
        FOREIGN KEY (`idfactory`)
        REFERENCES `madeIn`.`factory` (`factoryid`)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
