-- MySQL Script generated by MySQL Workbench
-- Mon 26 Dec 2016 15:05:30 NZDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema madeIn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema madeIn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `madeIn` DEFAULT CHARACTER SET utf8 ;
USE `madeIn` ;

-- -----------------------------------------------------
-- Table `madeIn`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`Country` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`Country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `code` VARCHAR(2),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madeIn`.`manufacturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`manufacturer` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `idcountryman` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_address_Country3`
    FOREIGN KEY (`idcountryman`)
    REFERENCES `madeIn`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  
ENGINE = InnoDB;

CREATE INDEX `fk_address_Country3_idx` ON `madeIn`.`manufacturer` (`idcountryman` ASC);

CREATE UNIQUE INDEX `idmanufacturer_UNIQUE` ON `madeIn`.`manufacturer` (`id` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`products` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` TEXT NULL,
  `barcode` VARCHAR(40),
  `idmanufacturer` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_manufacturer1`
    FOREIGN KEY (`idmanufacturer`)
    REFERENCES `madeIn`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `madeIn`.`products` (`id` ASC);

CREATE INDEX `fk_products_manufacturer1_idx` ON `madeIn`.`products` (`idmanufacturer` ASC);

-- -----------------------------------------------------
-- Table `madeIn`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`state` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_address_Country2`
    FOREIGN KEY (`idcountry`)
    REFERENCES `madeIn`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_address_Country2_idx` ON `madeIn`.`state` (`idcountry` ASC);

-- -----------------------------------------------------
-- Table `madeIn`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`city` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `stateid` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_address_state2`
    FOREIGN KEY (`stateid`)
    REFERENCES `madeIn`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_address_state2_idx` ON `madeIn`.`city` (`stateid` ASC);

-- -----------------------------------------------------
-- Table `madeIn`.`factory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`factory` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`factory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `idaddress` INT NULL,
  `idmanufacturer` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idfactory_UNIQUE` ON `madeIn`.`factory` (`id` ASC);



-- -----------------------------------------------------
-- Table `madeIn`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`address` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL,
  `city` INT NOT NULL,
  `state` INT NOT NULL,
  `country` INT NOT NULL,
  `zip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city`)
    REFERENCES `madeIn`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_Country1`
    FOREIGN KEY (`country`)
    REFERENCES `madeIn`.`Country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_state1`
    FOREIGN KEY (`state`)
    REFERENCES `madeIn`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_address_city1_idx` ON `madeIn`.`address` (`city` ASC);

CREATE INDEX `fk_address_Country1_idx` ON `madeIn`.`address` (`country` ASC);

CREATE INDEX `fk_address_state1_idx` ON `madeIn`.`address` (`state` ASC);

CREATE UNIQUE INDEX `iduser_UNIQUE` ON `madeIn`.`address` (`id` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`manufacturer_factory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`manufacturer_factory` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`manufacturer_factory` (
  `idmanufacturer` INT NULL,
  `idfactory` INT NULL,
  CONSTRAINT `fk_manufacturer_factory_manufacturer1`
    FOREIGN KEY (`idmanufacturer`)
    REFERENCES `madeIn`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manufacturer_factory_factory1`
    FOREIGN KEY (`idfactory`)
    REFERENCES `madeIn`.`factory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_manufacturer_factory_manufacturer1_idx` ON `madeIn`.`manufacturer_factory` (`idmanufacturer` ASC);

CREATE INDEX `fk_manufacturer_factory_factory1_idx` ON `madeIn`.`manufacturer_factory` (`idfactory` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`factory_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`factory_address` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`factory_address` (
  `idfactory` INT NOT NULL,
  `idaddress` INT NOT NULL,
  CONSTRAINT `fk_factory_address_factory1`
    FOREIGN KEY (`idfactory`)
    REFERENCES `madeIn`.`factory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factory_address_address1`
    FOREIGN KEY (`idaddress`)
    REFERENCES `madeIn`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_factory_address_factory1_idx` ON `madeIn`.`factory_address` (`idfactory` ASC);

CREATE INDEX `fk_factory_address_address1_idx` ON `madeIn`.`factory_address` (`idaddress` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`user` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`user` (
  `username` VARCHAR(16) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT NOT NULL AUTO_INCREMENT,
  `products_contributed` INT NULL,
  PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `iduser_UNIQUE` ON `madeIn`.`user` (`id` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`contribution_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`contribution_type` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`contribution_type` (
  `idcontribution` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontribution`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madeIn`.`product_contributor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`product_contributor` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`product_contributor` (
  `idproducts` INT NULL,
  `iduser` INT NOT NULL,
  `contribution_type` INT NULL,
  CONSTRAINT `fk_product_contributor_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `madeIn`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_contributor_products1`
    FOREIGN KEY (`idproducts`)
    REFERENCES `madeIn`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_contributor_contribution_type1`
    FOREIGN KEY (`contribution_type`)
    REFERENCES `madeIn`.`contribution_type` (`idcontribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_contributor_user1_idx` ON `madeIn`.`product_contributor` (`iduser` ASC);

CREATE INDEX `fk_product_contributor_products1_idx` ON `madeIn`.`product_contributor` (`idproducts` ASC);

CREATE INDEX `fk_product_contributor_contribution_type1_idx` ON `madeIn`.`product_contributor` (`contribution_type` ASC);


-- -----------------------------------------------------
-- Table `madeIn`.`manufacturer_contributor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madeIn`.`manufacturer_contributor` ;

CREATE TABLE IF NOT EXISTS `madeIn`.`manufacturer_contributor` (
  `idmanufacturer` INT NULL,
  `contribution_type` INT NULL,
  `iduser` INT NOT NULL,
  CONSTRAINT `fk_manufacturer_contributor_contribution_type1`
    FOREIGN KEY (`contribution_type`)
    REFERENCES `madeIn`.`contribution_type` (`idcontribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manufacturer_contributor_manufacturer1`
    FOREIGN KEY (`idmanufacturer`)
    REFERENCES `madeIn`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manufacturer_contributor_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `madeIn`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_manufacturer_contributor_contribution_type1_idx` ON `madeIn`.`manufacturer_contributor` (`contribution_type` ASC);

CREATE INDEX `fk_manufacturer_contributor_manufacturer1_idx` ON `madeIn`.`manufacturer_contributor` (`idmanufacturer` ASC);

CREATE INDEX `fk_manufacturer_contributor_user1_idx` ON `madeIn`.`manufacturer_contributor` (`iduser` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
